version: '3.8'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'uvicorn main:app --host 0.0.0.0 --port 8000 --reload'
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - WAREHOUSE_URL=
      - SALES_URL=
      - ACCOUNTING_URL=
