# Generated by Django 4.2.5 on 2023-09-09 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_type', models.PositiveSmallIntegerField(
                    choices=[(1, 'Cash On Delivery'), (2, 'Card')], default=1)
                 ),
                ('status', models.PositiveSmallIntegerField(
                    choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'In-Transit'), (4, 'Delivered')], default=1)
                 ),
                ('product_sku', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='order', to='core.customer')
                 ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
