version: '3.8'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "./wait-for-mysql.sh", "db", "3306", "python", "manage.py", "runserver", "0.0.0.0:8002"]
    ports:
      - 8002:8002
    volumes:
      - .:/accounting
    working_dir: /accounting
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://0.0.0.0:8002 || exit 1" ]
      interval: 5s
      timeout: 10s
      retries: 3
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: accounting
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 33067:3306

volumes:
  db-data:
