# Generated by Django 4.2.5 on 2023-09-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='type',
        ),
        migrations.DeleteModel(
            name='RevenueType',
        ),
    ]
